#!/usr/bin/cmake -P

# first argument - preset name

IF(NOT DEFINED CMAKE_ARGV3)
    SET(PRESET_NAME "default")
ELSE()
    SET(PRESET_NAME ${CMAKE_ARGV3})
ENDIF()

CMAKE_PATH(GET CMAKE_SCRIPT_MODE_FILE PARENT_PATH SCRIPT_DIR)

EXECUTE_PROCESS(
    COMMAND ${CMAKE_COMMAND} --build --preset ${PRESET_NAME}
    WORKING_DIRECTORY ${SCRIPT_DIR}
    COMMAND_ERROR_IS_FATAL ANY
)
