#!/usr/bin/cmake -P

CMAKE_PATH(GET CMAKE_SCRIPT_MODE_FILE PARENT_PATH SCRIPT_DIR)

IF(DEFINED CMAKE_ARGV3)
    SET(ASTERISK_VERSION_NUM ${CMAKE_ARGV3})
ELSE()
    SET(ASTERISK_VERSION_NUM 180000) # default value    
ENDIF()

EXECUTE_PROCESS(
    COMMAND ${CMAKE_COMMAND} -DASTERISK_VERSION_NUM=${ASTERISK_VERSION_NUM} --preset openwrt
    WORKING_DIRECTORY ${SCRIPT_DIR}
    COMMAND_ERROR_IS_FATAL ANY
)
