#!/usr/bin/cmake -P

# first argument - preset
# second argument - Asterisk version

IF(NOT DEFINED CMAKE_ARGV3)
    SET(PRESET_NAME "default")
ELSEIF(${CMAKE_ARGV3} STREQUAL "default")
    SET(PRESET_NAME "default")
ELSEIF(${CMAKE_ARGV3} STREQUAL "arm")
    SET(PRESET_NAME "arm")
ELSEIF(${CMAKE_ARGV3} STREQUAL "arm64")
    SET(PRESET_NAME "arm64")
ELSE()
    MESSAGE(FATAL_ERROR "Unknown architecture: ${CMAKE_ARGV3}")
ENDIF()

IF(NOT DEFINED CMAKE_ARGV4)
    SET(ASTERISK_VERSION_NUM 180000) # default value
ELSE()
    SET(ASTERISK_VERSION_NUM ${CMAKE_ARGV4})
ENDIF()

CMAKE_PATH(GET CMAKE_SCRIPT_MODE_FILE PARENT_PATH SCRIPT_DIR)

EXECUTE_PROCESS(
    COMMAND ${CMAKE_COMMAND} -DASTERISK_VERSION_NUM=${ASTERISK_VERSION_NUM} --preset ${PRESET_NAME}
    WORKING_DIRECTORY ${SCRIPT_DIR}
    COMMAND_ERROR_IS_FATAL ANY
)
