#!/usr/bin/cmake -P

IF(NOT DEFINED CMAKE_ARGV3)
    SET(PRESET_NAME "package")
ELSEIF(${CMAKE_ARGV3} STREQUAL "arm")
    SET(PRESET_NAME "package-arm")
ELSEIF(${CMAKE_ARGV3} STREQUAL "arm64")
    SET(PRESET_NAME "package-arm64")
ELSE()
    MESSAGE(FATAL_ERROR "Unknown architecture: ${CMAKE_ARGV3}")
ENDIF()

CMAKE_PATH(GET CMAKE_SCRIPT_MODE_FILE PARENT_PATH SCRIPT_DIR)

EXECUTE_PROCESS(
    COMMAND ${CMAKE_COMMAND} --build --preset ${PRESET_NAME}
    WORKING_DIRECTORY ${SCRIPT_DIR}
    COMMAND_ERROR_IS_FATAL ANY
)
