#
# make-feeds-conf.cmake
#
IF(EXISTS $ENV{DESTDIR})
    SET(OPENWRT_INSTALL_DIR $ENV{DESTDIR})
    CMAKE_PATH(APPEND OPENWRT_INSTALL_DIR ${CMAKE_INSTALL_PREFIX} ${CMAKE_INSTALL_COMPONENT})
ELSE()
    SET(OPENWRT_INSTALL_DIR ${CMAKE_INSTALL_PREFIX})
    CMAKE_PATH(APPEND OPENWRT_INSTALL_DIR ${CMAKE_INSTALL_COMPONENT})
ENDIF()
CMAKE_PATH(APPEND OPENWRT_INSTALL_DIR feed OUTPUT_VARIABLE FEED_DIR)

CONFIGURE_FILE(
    ${CMAKE_INSTALL_COMPONENT}/feeds.conf.in ${OPENWRT_INSTALL_DIR}/feeds-strskx.conf @ONLY
)
