#!/bin/bash -e

./configure \
    --with-download-cache=/build/cache \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --disable-xmldoc \
    --disable-dev-mode \
    --disable-internal-poll \
    --without-oss \
    --without-portaudio \
    --without-jack \
    --without-x11 \
    --without-vpb \
    --without-gtk2 \
    --without-gmime \
    --without-sdl \
    --without-avcodec \
    --without-bluetooth \
    --without-iodbc \
    --without-imap \
    --without-inotify \
    --without-sqlite \
    --without-sndfile \
    --without-mysqlclient \
    --without-postgres \
    --without-iksemel \
    --without-openr2 \
    --without-radius \
    --without-resample \
    --without-spandsp \
    --without-tds \
    --without-neon29 \
    --without-neon \
    --without-pri \
    --without-ss7 \
    --without-dahdi \
    --without-misdn \
    --without-suppserv \
    --without-tonezone \
    --without-fftw3 \
    --without-unbound \
    --without-vorbis \
    --without-speex \
    --without-speexdsp \
    --without-ogg \
    --without-ilbc \
    --without-opus \
    --without-opusfile \
    --without-vpb \
    --without-jansson-bundled

make menuselect.makeopts

menuselect/menuselect \
    --enable LOW_MEMORY \
    --disable BUILD_NATIVE \
    --disable codec_speex \
    --disable codec_ilbc \
    --disable codec_lpc10 \
    --disable codec_g726 \
    --disable codec_adpcm \
    --enable func_speex  \
    --disable cdr_syslog \
    --disable cdr_sqlite3_custom \
    --disable cel_sqlite3_custom \
    --disable format_gsm \
    --disable format_wav_gsm \
    --disable format_siren7 \
    --disable format_siren14 \
    --disable format_ilbc \
    --disable format_g719 \
    --disable format_g723 \
    --disable format_g726 \
    --disable format_h263 \
    --disable format_h264 \
    --disable format_vox \
    --disable res_fax \
    --disable res_fax_spandsp \
    --disable res_format_attr_h263 \
    --disable res_format_attr_h264 \
    --disable res_config_pgsql \
    --disable res_format_attr_siren14 \
    --disable res_format_attr_siren7 \
    --disable res_format_attr_vp8 \
    --disable res_format_attr_ilbc \
    --disable res_speech \
    --disable res_config_ldap \
    --disable res_format_attr_silk \
    --enable res_snmp \
    --disable res_adsi \
    --disable res_monitor \
    --disable app_festival \
    --disable app_mp3 \
    --disable app_ices \
    --disable app_image \
    --disable app_sms \
    --disable app_nbscat \
    --enable app_url \
    --disable app_test \
    --enable app_flash \
    --disable chan_sip \
    --disable chan_skinny \
    --disable chan_unistim \
    --disable chan_iax2 \
    --disable chan_mgcp \
    --disable chan_motif \
    --disable astdb2sqlite3 \
    --disable astdb2bdb \
    --disable astcanary \
    --disable CORE-SOUNDS-EN-WAV \
    --disable CORE-SOUNDS-EN-GSM \
    --disable CORE-SOUNDS-EN-G722 \
    --disable MOH-OPSOUND-WAV \
    --disable MOH-OPSOUND-GSM \
    --disable MOH-OPSOUND-G722 \
    --disable EXTRA-SOUNDS-EN-WAV \
    --disable EXTRA-SOUNDS-EN-GSM \
    --disable EXTRA-SOUNDS-EN-G722 \
    menuselect.makeopts